### ISSUE TITLE
Earth Dataset Access

### ISSUE THREAD

**Issue by Eyotoye** [facebookresearch/riemannian-fm#2]
Hello!

I'm currently working to replicate the results presented in your paper and have noticed that the dataset for Earth mentioned in the code ultimately points to four separate files: **volcano.csv**, among others. Unfortunately, I haven't been able to find a way to download these datasets.

Would it be possible for you to kindly provide me with access to these datasets? I am eager to explore your work further and appreciate any assistance you can provide.

Thank you very much.

**Comment by dvthuytran** [comment]
I think the authors already put the link [here](https://github.com/facebookresearch/riemannian-fm?tab=readme-ov-file#data).

**Comment by rtqichen** [comment]
I just tested and it works for me. Are you having trouble downloading the data?

**Comment by Eyotoye** [comment]
> I think the authors already put the link [here](https://github.com/facebookresearch/riemannian-fm?tab=readme-ov-file#data).



> I just tested and it works for me. Are you having trouble downloading the data?

It works. In fact I did download the .zip file but could not find the earth data due to unknown reason. I'm not so sure but it seems that there was only a synthesized dataset then. However, when downloading and unzipping it today, it is complete. Sorry for bothering!
